language: python

sudo: false

addons:
  apt:
    packages:
    - g++
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libatlas-dev

python:
- '2.7'

before_install:
- pip install --quiet --upgrade pip

install:
- pip install --quiet --upgrade numpy
- python setup.py develop

script: py.test FlowCytometryTools
