language: python

sudo: false

cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

python:
- '2.7'

before_install:
  - pip install -U pip
  - pip install wheel

install:
  - pip wheel -r requirements.txt
  - pip wheel -r requirements.test.txt
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt

script: 
  - py.test FlowCytometryTools/ --cov FlowCytometryTools -v --cov-report term-missing

after_success:
  - coveralls
