language: python

sudo: false

cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

addons:
  apt:
    packages:
    - g++
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libatlas-dev

python:
- '2.7'

before_install:
  - pip install -U pip
  - pip install wheel

install:
  - pip wheel -r requirements
  - pip install -r requirements

script: 
  - py.test FlowCytometryTools
